services:
  - type: web
    name: inventory
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn inventory.wsgi:application --bind 0.0.0.0:$PORT
